# Generated by Django 5.2.8 on 2025-11-23 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_at'], name='poll_poll_created_be8aef_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at'], name='poll_poll_expires_c5dfa1_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='poll_questi_created_5101b4_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['question'], name='poll_vote_questio_4068c4_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['choice'], name='poll_vote_choice__2c1103_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['user'], name='poll_vote_user_id_028d97_idx'),
        ),
    ]
